# basic
title: believe
subtitle: 笔直向前，说到做到
favicon: /images/favicon.ico

#logo
logo: /images/logo.jpg

# >>> Conments 评论系统 <<<
# duoshuo-comment  多说
duoshuo_shortname:
#disqus_shortname   disqus
disqus_shortname:
#wangyi_shortname  网易
wangyi_shortname:
#changyan_shortname  畅言
changyan_shortname: true

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# nav #
nav:
  - id: 首页
    url: .
    icon: home
  - id: 归档
    url: archives
    icon: archive
  - id: 关于
    url: about
    icon: user
  - id: 项目
    url: project
    icon: folder-open
  - id: 相册
    url: photo
    icon: photo
  - id: 留言
    url: guestbook
    icon: edit
 # - id: RSS
  #  url: atom.xml
   # icon: send

# cover
cover_img: http://img.elife.com/forum/201502/04/163739c7icmreird0c9a9m.jpg
cover_avator: /images/Avatar.jpg
cover_info: 欢迎来到我的博客</br>by:迷途羔羊

# photo(four pictures every line)
photo:
  - title: 上海·外滩
    url: http://oct3pmpde.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720160911111234_Snapseed_meitu_3.jpg
  - title: 上海·城隍庙
    url: http://oct3pmpde.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720160911105703_Snapseed_meitu_4.jpg
  - title: 上海·外滩
    url: http://oct3pmpde.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720160911112212_Snapseed_meitu_2.jpg
  - title: 上海·城隍庙
    url: http://oct3pmpde.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720160911105720_Snapseed_meitu_1.jpg
  - title: 谢霆锋
    url: http://oct3pmpde.bkt.clouddn.com/23432.jpg
  - title: 朱茵
    url: http://oct3pmpde.bkt.clouddn.com/278f3ec3472f45aca025d6b7f1048ce8fda727217c64-tJA5fE_fw658_meitu_2.jpg
  - title: 萌
    url: http://oct3pmpde.bkt.clouddn.com/93a3663ce5a120df2187d88dee6b611e4d6bb0fd890e-Ayk04S_fw658_meitu_5.jpg
  - title: 谢霆锋
    url: http://oct3pmpde.bkt.clouddn.com/234.jpg
  - title: 新垣结衣
    url: http://oct3pmpde.bkt.clouddn.com/5406bfb524dedd8d8d583f851de02a6f954b8cb63a313-KkBPG0_fw658_meitu_5.jpg
  - title: 萌
    url: http://oct3pmpde.bkt.clouddn.com/img3_meitu_8.jpg
  - title: 萌
    url: http://oct3pmpde.bkt.clouddn.com/1be693d8c060f36425ff18c2c6bd74297e124115481ef-ORfbts_fw658_meitu_4.jpg
  - title: 新垣结衣
    url: http://oct3pmpde.bkt.clouddn.com/efffa4c7e22d967269410e4ee5a8a22f963840312e32c-0Xv1LH_fw658_meitu_6.jpg
  - title: 旅行
    url: http://oct3pmpde.bkt.clouddn.com/9a75825d20a21a59472d7f17f758682c82fcadd025169-D9G2Hv_fw658_meitu_11.jpg
  - title: 萌
    url: http://oct3pmpde.bkt.clouddn.com/15307563afb5f071d66161bf7cdbdb496ea5674814c5f-GKX9ys_fw658_meitu_3.jpg
  - title: 无脸男
    url: http://oct3pmpde.bkt.clouddn.com/ad01a45561cee108d12f25f09930c80f2f2a91238510-Ys0wNX_fw658_meitu_1.jpg
  - title: PC
    url: http://oct3pmpde.bkt.clouddn.com/61dd6485c9202285fc763bda7e79dbe389883401bed7b-wspi2M_fw658_meitu_7.jpg

# project #
project:
  - title: 金石金融研究院
    url: http://blog.xierongsheng.science/
    sub: 刚开始从事web前端时所做的网页
    language: 网站
  - title: 我的博客
    url: http://xierongsheng.science/
    sub: 采用hexo-theme-believe主题的博客
    language: blog
  - title: 营销活动页1
    url: https://x447618716.github.io/special7/
    sub: 刚开始从事web前端时所做的网页
    language: 活动1
  - title: 营销活动页2
    url: https://x447618716.github.io/special6/
    sub: 刚开始从事web前端时所做的网页
    language: 手机页
  - title: 营销活动页3
    url: https://x447618716.github.io/special1/
    sub: 刚开始从事web前端时所做的网页
    language: 活动页3
  - title: 营销活动页4
    url: https://x447618716.github.io/special4/
    sub: 刚开始从事web前端时所做的网页
    language: 活动页4
  - title: 根据身份证省市区三联
    url: https://x447618716.github.io/Triad_assembly/
    sub: 身份证省市区三联
    language: html

# 百度、谷歌站长验证。填写 HTML 标签 content
# Fill in Google Analytics tracking ID, #e.g. UA-XXXXX-X, or Baidu Analytics hash key
google_analytics: UA-102262786-1
baidu_analytics: 1d809c37c7b29de1973f335c44cb57b0

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/x447618716
  #weibo: http://weibo.com/th0527
  #twitter: https://twitter.com
  #facebook: https://facebook.com

footer: 迷途羔羊的技术小屋
