# basic
title: believe
subtitle: 笔直向前，说到做到
favicon: /images/Other/favicon.ico

#logo
logo: /images/Other/logo.jpg

# >>> Conments 评论系统 <<<
# duoshuo-comment  多说
duoshuo_shortname:
#disqus_shortname   disqus
disqus_shortname:
#wangyi_shortname  网易
wangyi_shortname:
#changyan_shortname  畅言
changyan_shortname: true

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# nav #
nav:
  - id: 首页
    url: .
    icon: home
  - id: 归档
    url: archives
    icon: archive
  - id: 关于
    url: about
    icon: user
  - id: 项目
    url: project
    icon: folder-open
  - id: 相册
    url: photo
    icon: photo
  - id: 留言
    url: guestbook
    icon: edit
 # - id: RSS
  #  url: atom.xml
   # icon: send

# cover
cover_img: http://img.elife.com/forum/201502/04/163739c7icmreird0c9a9m.jpg
cover_avator: /images/Other/Avatar.jpg
cover_info: 欢迎来到我的博客</br>by:迷途羔羊

# photo(four pictures every line)
photo:
  - title: 海贼王
    url: ../images/Love/311664.jpg
  - title: 火影忍者
    url: ../images/Love/292099.jpg
  - title: 秦时明月
    url: ../images/Love/297857.jpg
  - title: 名侦探柯南
    url: ../images/Love/287451.jpg
  - title: 罪恶王冠
    url: ../images/Love/309983.jpg
  - title: 妖精的尾巴
    url: ../images/Love/261381.jpg
  - title: 进军的巨人
    url: ../images/Love/245986.jpg
  - title: 夏目友人帐
    url: ../images/Love/189811.png
  - title: 路人女主养成计划
    url: ../images/Love/289701.jpg
  - title: 超神学院
    url: ../images/Love/314693.jpg
  - title: 刀剑神域
    url: ../images/Love/306093.png
  - title: 魁拔
    url: ../images/Love/290488.jpg

# project #
project:
  - title: 金石金融研究院
    url: http://blog.xierongsheng.science/
    sub: 刚开始从事web前端时所做的网页
    language: 网站
  - title: 我的博客
    url: http://xierongsheng.science/
    sub: 采用hexo-theme-believe主题的博客
    language: blog
  - title: 营销活动页1
    url: https://x447618716.github.io/special7/
    sub: 刚开始从事web前端时所做的网页
    language: 活动1
  - title: 营销活动页2
    url: https://x447618716.github.io/special6/
    sub: 刚开始从事web前端时所做的网页
    language: 手机页
  - title: 营销活动页3
    url: https://x447618716.github.io/special1/
    sub: 刚开始从事web前端时所做的网页
    language: 活动页3
  - title: 营销活动页4
    url: https://x447618716.github.io/special4/
    sub: 刚开始从事web前端时所做的网页
    language: 活动页4
  - title: 根据身份证省市区三联
    url: https://x447618716.github.io/Triad_assembly/
    sub: 身份证省市区三联
    language: html

# 百度、谷歌站长验证。填写 HTML 标签 content
# Fill in Google Analytics tracking ID, #e.g. UA-XXXXX-X, or Baidu Analytics hash key
google_analytics: UA-102262786-1
baidu_analytics: 1d809c37c7b29de1973f335c44cb57b0

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/x447618716
  #weibo: http://weibo.com/th0527
  #twitter: https://twitter.com
  #facebook: https://facebook.com

footer: 迷途羔羊的技术小屋
